name: Enforce Docker retention policy

on:
  schedule:
    - cron: 20 0 * * 4

jobs:
  enforce_docker_retention_policy:
    name: Enforce Docker retention policy
    uses: ./.github/workflows/enforce_docker_retention_policy.yml
    with:
      image_names: >
        ngwsp
    secrets:
      container_registry_token: ${{ secrets.GITHUB_TOKEN }}
